version: "3.7"
services:
  backend:
    image: ms-sp-soporte-ti-obtiene-datos-geografia-pga:latest
    container_name: backend
    build:
      context: .
    ports:
      - "9090:9090"
    depends_on:
      - redis-db
  redis-db:
    image: redis:alpine
    container_name: redis-db
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    command: redis-server --requirepass E3gGnad5XhQj9VqCWmYYOLe8UvPFt9zq4AzCaA5bawE=
    healthcheck:
      test: [ "CMD", "redis-cli", "auth", "E3gGnad5XhQj9VqCWmYYOLe8UvPFt9zq4AzCaA5bawE=", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10