server:
  port: 9090
  servlet:
    context-path: /ms-sp-soporte-ti-obtiene-datos-geografia-pga/v1

spring:
  application:
    name: ms-sp-soporte-ti-obtiene-datos-geografia-pga-v1
  main:
    allow-bean-definition-overriding: true

  codec:
    max-in-memory-size: 20MB

  redis:
    host: rdsspgeografiaCrt0100.redis.cache.windows.net
    password: d8IEBNkoKUdxOgqY1XKMaLu4CGgCZZvc9AzCaNY6EqI=
    port: 6380
    ssl: true
    jedis :
      pool:
        max-active: 500
        max-idle: 10
        min-idle: 1
        max-wait: 360s

api:
  support:
    base:
      ubigeo:
        url: http://localhost:9080/ubigeo
        Authorization: 1234557aa
        ocp-apim-subscription-key: 926ec90111ea4d3bb44699fa01f01c1baa
        ocp-apim-trace: true
webclient:
  connect:
    time-out.millis: 50000
  read:
    time-out.seconds: 50
  write:
    time-out.seconds: 50
  circuit-breaker:
    time-out.seconds: 4

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  level:
    org.springframework.web: ERROR
    pe.com.pacifico.kuntur: DEBUG
    org.hibernate: ERROR
